fix: Add support for webpack 5 module federation references
liady/webpack-node-externals pull request #92
Opened 2021-01-15 01:38 UTC by jacob-ebey

Without this webpack tries to import an external called "webpack/container/reference/remote" that does not exist when referencing a federated remote.

2021-01-15 18:25 UTC, liady requested changes

2021-01-15 18:25 UTC, liady commented on index.js
> +    var allowlist = [].concat(options.allowlist || [/^webpack\/container\/reference\//]);
Should `/^webpack\/container\/reference\//` always be present? If so - maybe it's better to have 
```
allowlist = [/^webpack\/container\/reference\//].concat(options.allowlist || []);
```

2021-01-17 00:44 UTC, jacob-ebey commented
@liady Feel free to ship this at any point.

2021-01-29 17:53 UTC, jacob-ebey commented
@liady Please get this merged so I stop getting the same "my node bundle doesn't work" comment.

2021-01-29 17:59 UTC, liady commented
@jacob-ebey yes, planning to, just thinking about how to do it in a generic way, and add a test.
Do you know if it breaks webpack < 5 compatibility? This might have to be a major version change.

2021-01-29 18:56 UTC, jacob-ebey commented
Should be fine. `webpack/container/reference/xxx` was chosen because it's stupid unlikely anyone has created npm modules or aliased anything such. Major version is fine with me if it makes you feel more comfortable. No tears on this end, I just want to see this release so I stop getting the same comments / questions.

2021-04-19 18:04 UTC, ScriptedAlchemy commented
@liady please consider merging this in

2021-04-21 10:13 UTC, liady commented
@jacob-ebey @ScriptedAlchemy added to `webpack-node-externals@3.0.0`, please check if it solves it.

2021-04-21 10:55 UTC, liady commented
Closing this as it should be resolved in version 3.0.0, let me know if it doesn't work.

2021-04-21 10:55 UTC, closed without merging